# Generated by Django 2.2 on 2024-07-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('flier', models.ImageField(blank=True, upload_to='fliers/')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='speakers/')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Programme')),
            ],
        ),
    ]
