# Generated by Django 2.2 on 2024-07-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20240708_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='date',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='programmeevent',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
