# Generated by Django 2.2 on 2024-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20240708_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='venue',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
