# Generated by Django 2.2 on 2024-07-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_programme_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='theme',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
