# Generated by Django 2.2 on 2022-07-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('gender', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('Phonenumber', models.CharField(blank=True, max_length=300)),
                ('Emailaddress', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(blank=True, max_length=300)),
                ('level', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
