# Generated by Django 2.2 on 2022-07-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='School',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='level',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=300),
        ),
    ]
