# Generated by Django 2.2 on 2022-07-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20220719_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='status',
        ),
        migrations.AddField(
            model_name='data',
            name='Church',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='data',
            name='Occupation',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Business', 'Business'), ('Enterprenuer', 'Enterprenuer'), ('Civil Servant', 'Civil Servant'), ('Politician', 'Politician')], max_length=300),
        ),
        migrations.AddField(
            model_name='data',
            name='Zone',
            field=models.CharField(blank=True, choices=[('Awada', 'Awada'), ('Ugwuagba', 'Ugwuagba'), ('Holy Trinity', 'HolyTrinity'), ('Good Shepherd', 'Good Shepherd')], max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Jss1', 'Jss1'), ('Jss2', 'Jss2'), ('Jss3', 'Jss3'), ('Ss1', 'Ss1'), ('Ss2', 'Ss2'), ('Ss3', 'Ss3'), ('Aspirant', 'Aspirant'), ('100l', '100l'), ('200l', '200l'), ('300l', '300l'), ('400l', '400l'), ('500l', '500l'), ('600l', '600l'), ('700l', '700l'), ('Graduate', 'Graduate'), ('Masters Student', 'Masters Student'), ('Phd Student', 'Phd Student')], max_length=300),
        ),
    ]
