# Generated by Django 2.2 on 2022-07-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_subcription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaminglink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mixlr', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
