# Generated by Django 2.2 on 2022-07-23 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_streaminglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
