# Generated by Django 2.2 on 2023-07-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_data_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streaminglink',
            name='Telegram',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
