# Generated by Django 2.2 on 2024-07-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20230716_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Occupation',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Youth Corp', 'Youth Corp'), ('Business', 'Business'), ('Enterprenuer', 'Enterprenuer'), ('Civil Servant', 'Civil Servant'), ('Politician', 'Politician'), ('Private Worker', 'Private Worker')], max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Jss1', 'Jss1'), ('Jss2', 'Jss2'), ('Jss3', 'Jss3'), ('Ss1', 'Ss1'), ('Ss2', 'Ss2'), ('Ss3', 'Ss3'), ('Aspirant', 'Aspirant'), ('Jupeb', 'Jupeb'), ('Pre-Science/Pre-degree', 'Pre-Science/Pre-degree'), ('100l', '100l'), ('200l', '200l'), ('300l', '300l'), ('400l', '400l'), ('500l', '500l'), ('600l', '600l'), ('700l', '700l'), ('Graduate', 'Graduate'), ('Masters Student', 'Masters Student'), ('Phd Student', 'Phd Student')], max_length=300),
        ),
    ]
