# Generated by Django 2.2 on 2024-07-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_programme_theme'),
        ('registration', '0010_auto_20240708_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.Programme'),
        ),
    ]
