# Generated by Django 2.2 on 2024-07-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_data_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_registered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
