# Generated by Django 2.2 on 2022-07-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=300)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=300)),
                ('Day_of_Birth', models.IntegerField()),
                ('Month_of_Birth', models.CharField(blank=True, max_length=300)),
                ('Phonenumber', models.CharField(blank=True, max_length=300)),
                ('marital_Status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=300)),
                ('Name_of_spouse', models.CharField(blank=True, max_length=300)),
                ('Residential_address', models.CharField(blank=True, max_length=300)),
                ('Residential_LGA', models.CharField(blank=True, max_length=300)),
                ('Residential_State', models.CharField(blank=True, max_length=300)),
                ('Home_town', models.CharField(blank=True, max_length=300)),
                ('LGA', models.CharField(blank=True, max_length=300)),
                ('State', models.CharField(blank=True, max_length=300)),
                ('Hobbies', models.CharField(blank=True, max_length=300)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=300)),
                ('Occupation', models.CharField(blank=True, choices=[('Student', 'Student'), ('Business', 'Business'), ('Enterprenuer', 'Enterprenuer'), ('Civil Servant', 'Civil Servant'), ('Politician', 'Politician'), ('Private Worker', 'Private Worker')], max_length=300)),
                ('profession', models.CharField(blank=True, max_length=300)),
                ('Name_of_organization', models.CharField(blank=True, max_length=300)),
                ('School', models.CharField(blank=True, max_length=300)),
                ('level', models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Jss1', 'Jss1'), ('Jss2', 'Jss2'), ('Jss3', 'Jss3'), ('Ss1', 'Ss1'), ('Ss2', 'Ss2'), ('Ss3', 'Ss3'), ('Aspirant', 'Aspirant'), ('Jupeb', 'Jupeb'), ('Pre-Science/Pre-degree', 'Pre-Science/Pre-degree'), ('100l', '100l'), ('200l', '200l'), ('300l', '300l'), ('400l', '400l'), ('500l', '500l'), ('600l', '600l'), ('700l', '700l'), ('Graduate', 'Graduate'), ('Youth Corp', 'Youth Corp'), ('Masters Student', 'Masters Student'), ('Phd Student', 'Phd Student')], max_length=300)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='otherinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=300)),
                ('Church', models.CharField(blank=True, max_length=300)),
                ('Zone', models.CharField(blank=True, choices=[('Awada', 'Awada'), ('Ugwuagba', 'Ugwuagba'), ('Holy Trinity', 'HolyTrinity'), ('Good Shepherd', 'Good Shepherd'), ('None', 'None')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='socialprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('Whatsapp', models.CharField(blank=True, max_length=300)),
                ('twitter', models.CharField(blank=True, max_length=300)),
                ('instagram', models.CharField(blank=True, max_length=300)),
                ('facebook', models.CharField(blank=True, max_length=300)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
