# Generated by Django 2.2 on 2022-08-05 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Directory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.RemoveField(
            model_name='career',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='otherinfo',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='Name',
        ),
        migrations.AddField(
            model_name='bio',
            name='LastName',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='bio',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='bio',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='career',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
