# Generated by Django 2.2 on 2022-08-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0002_auto_20220805_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='Branch',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='bio',
            name='Church',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='bio',
            name='Zone',
            field=models.CharField(blank=True, choices=[('Awada', 'Awada'), ('Ugwuagba', 'Ugwuagba'), ('Holy Trinity', 'HolyTrinity'), ('Good Shepherd', 'Good Shepherd'), ('None', 'None')], max_length=300),
        ),
        migrations.AddField(
            model_name='bio',
            name='profilepicture',
            field=models.ImageField(blank=True, upload_to='assets'),
        ),
        migrations.AddField(
            model_name='career',
            name='Name_of_Business',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='career',
            name='current_location_Business',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.DeleteModel(
            name='otherinfo',
        ),
    ]
